### ISSUE TITLE
patterns.md should probably go away

### ISSUE THREAD

**Issue by mgttlinger** [ausgerechnet/spheroscope#18]
I suggest we incorporate the knowledge contained in the `patterns.md` into the new guidelines or the descriptions in `patterns.csv` otherwise this information is weirdly split across different files.

**Comment by ausgerechnet** [comment]
patterns.md is intended to assist when searching for the presence of any of the patterns in a given text. I don't think it's reasonable to merge this information into patterns.csv.

we can just have a separate sections in the guidelines.
