### ISSUE TITLE
result_table.html doesn't render properly

### ISSUE THREAD

**Issue by ausgerechnet** [ausgerechnet/spheroscope#39]
return of `spheroscope.queries.run_cmd()` at `queries/<id>/run/` looks fine, but the result table is not properly formatted: no text or slots are displayed

**Comment by ausgerechnet** [comment]
I'm not quite sure how this bug got introduced but it might be some change in behaviour of pandas (there's a multiindex of axis 1 involved).

**Comment by mgttlinger** [comment]
The whole thing was very fragile to begin with...

**Comment by mgttlinger** [comment]
what pandas version are you experiencing the issue with?

**Comment by ausgerechnet** [comment]
pandas==1.2.0

**Comment by ausgerechnet** [comment]
also horizontal scrolling should be allowed
