### ISSUE TITLE
make compatible with Safari on Apple

### ISSUE THREAD

**Issue by ausgerechnet** [ausgerechnet/spheroscope#41]
- when logging in on Safari, one gets redirected to the login-page
- this might be a problem with Flask's session name, see [here](https://stackoverflow.com/questions/24230582/flask-login-required-does-not-work-on-ie-and-safari])

**Comment by schtepf** [comment]
This [bug report](https://github.com/maxcountryman/flask-login/issues/605) for `flask-login` seems to describe exactly the symptoms observed with Spheroscope.

**Comment by schtepf** [comment]
The last post on [this page](https://spectrum.chat/apollo/apollo-client/unable-to-set-cookie-from-server-on-safari~e6a621bc-a9bd-469d-b0a9-8b7e93cf04a6) suggest the following explanation for the problem:

- Spheroscope instructs Flask to require the session cookie to be secure (`SESSION_COOKIE_SECURE = True` in the default config)
- but the connection to a dev server is plain HTTP and doesn't have a valid SSL certificate, so it's not secure
- Safari refuses to set the presumably fraudulent cookie, which seems to be the right thing to do

This **solution** has been **confirmed** to work on my MacBook Pro: login works fine after setting `SESSION_COOKIE_SECURE = False`.

The question remains: Why would Spheroscope use the incorrect setting for a development server?

**Comment by ausgerechnet** [comment]
> The question remains: Why would Spheroscope use the incorrect setting for a development server?

the example config might indeed be confusing, but a the end of the day it's your own responsibility what you write in your local config
