### ISSUE TITLE
default behaviour when start > end

### ISSUE THREAD

**Issue by ausgerechnet** [ausgerechnet/spheroscope#56]
some slots are defined in a way that start anchors can be _after_ end anchors, e.g. slot 1 of
- pattern3_why_does_entity_want_concept
- pattern3_entity_supporter_of_concept
- pattern3_entity_in_favour_of_concept
- pattern3_ellipsis_hoping_concept

this typically occurs when start anchors is corrected to the right (+1) or end anchors are corrected to the left (-1). what should the default behaviour for spheroscope be here?
1. discard these lines
2. switch start and end
3. singularize these slots (start = end)
4. raise an error

**Comment by nedykes** [comment]
I'm guessing that this would happen if there's only one token in between the anchors? In that case it would probably make sense to default to 3

**Comment by ausgerechnet** [comment]
an indeed this will be the default behaviour in #59
