### ISSUE TITLE
Hierarchical queries fail on "match" / "matchend" anchor points

### ISSUE THREAD

**Issue by nfdykes** [ausgerechnet/spheroscope#63]
When hierarchical queries encounter queries with a slot speficiation like {"0": ["match", 1], "1": [2, "matchend"]} 
e.g. pattern3_entity_in_favour_of_concept, it fails and throws a key error "['match'] not in index"

Presumably the same problem would apply for "matchend"

**Comment by ausgerechnet** [comment]
Are you using cwb-ccc v0.10.1?
